[tools]
python = "3"
"ubi:zigtools/zls" = "0.15.0"
usage = "latest"
zig = "0.15.1"

[tasks.build]
description = "Build for specific platform"
run = "python scripts/build.py"

[tasks.clean]
description = "Clean build artifacts"
run = "rm -rf zig-out .zig-cache"

[tasks.test]
description = "Run tests"
run = "zig build test"
