name: Build on Push

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE*"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE*"
      - ".gitignore"

jobs:
  get-version:
    name: Get version info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      short_hash: ${{ steps.version.outputs.short_hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version info
        id: version
        run: |
          # Extract version from build.zig.zon
          VERSION=$(grep -o '\.version = "[^"]*"' build.zig.zon | cut -d'"' -f2)
          SHORT_HASH=$(git rev-parse --short HEAD)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "short_hash=${SHORT_HASH}" >> $GITHUB_OUTPUT

  build:
    needs: get-version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      short_hash: ${{ needs.get-version.outputs.short_hash }}
