name: Nightly Build

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      force_build:
        description: "Force build even if no new commits"
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-new-commits:
    name: Check for new commits
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
      version: ${{ steps.version.outputs.version }}
      semver_version: ${{ steps.version.outputs.semver_version }}
      short_hash: ${{ steps.version.outputs.short_hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for new commits since last nightly
        id: check
        run: |
          # Get the latest nightly release
          LATEST_NIGHTLY=$(gh release list --limit 1 --json tagName,isPrerelease --jq '.[] | select(.isPrerelease == true) | .tagName' | head -1 || echo "")

          if [ -z "$LATEST_NIGHTLY" ]; then
            echo "No previous nightly releases found, will build"
            echo "should_build=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get the commit of the latest nightly release
          LATEST_COMMIT=$(gh release view "$LATEST_NIGHTLY" --json body --jq '.body' | grep -o 'Commit: [a-f0-9]\{6\}' | cut -d' ' -f2 || echo "")

          if [ -z "$LATEST_COMMIT" ]; then
            echo "Could not determine commit from latest nightly, will build"
            echo "should_build=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check if there are new commits since the latest nightly
          NEW_COMMITS=$(git rev-list --count "$LATEST_COMMIT"..HEAD 2>/dev/null || echo "1")

          if [ "$NEW_COMMITS" -gt 0 ] || [ "${{ github.event.inputs.force_build }}" = "true" ]; then
            echo "Found $NEW_COMMITS new commits since last nightly, will build"
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "No new commits since last nightly, skipping build"
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Get version info
        id: version
        if: steps.check.outputs.should_build == 'true'
        run: |
          # Extract version from build.zig.zon
          BASE_VERSION=$(grep -o '\.version = "[^"]*"' build.zig.zon | cut -d'"' -f2)
          SHORT_HASH=$(git rev-parse --short HEAD)

          # Parse semantic version components
          IFS='.' read -r major minor patch <<< "$BASE_VERSION"

          # Increment patch version for pre-release
          patch=$((patch + 1))

          # Generate date string in YYYYMMDD format
          DATE_STR=$(date -u '+%Y%m%d')

          # Create semantic version with pre-release suffix
          SEMVER_VERSION="${major}.${minor}.${patch}-dev.${DATE_STR}"

          echo "version=${BASE_VERSION}" >> $GITHUB_OUTPUT
          echo "semver_version=${SEMVER_VERSION}" >> $GITHUB_OUTPUT
          echo "short_hash=${SHORT_HASH}" >> $GITHUB_OUTPUT

  build:
    needs: check-new-commits
    if: needs.check-new-commits.outputs.should_build == 'true'
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.check-new-commits.outputs.version }}
      short_hash: ${{ needs.check-new-commits.outputs.short_hash }}

  release:
    name: Create nightly release
    runs-on: ubuntu-latest
    needs: [check-new-commits, build]
    if: needs.check-new-commits.outputs.should_build == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        env:
          SEMVER_VERSION: ${{ needs.check-new-commits.outputs.semver_version }}
        run: |
          mkdir -p release-assets
          # Copy all zip and tar.gz files from artifacts and rename them to include semver
          for file in $(find artifacts -type f \( -name "*.zip" -o -name "*.tar.gz" \)); do
            filename=$(basename "$file")
            # Extract the base name and extension
            if [[ "$filename" == *.tar.gz ]]; then
              base_name=$(basename "$filename" .tar.gz)
              extension=".tar.gz"
            else
              base_name=$(basename "$filename" .zip)
              extension=".zip"
            fi
            # Create new filename with semver version
            new_name="${base_name}-${SEMVER_VERSION}${extension}"
            cp "$file" "release-assets/${new_name}"
          done

      - name: Create nightly release
        env:
          BASE_VERSION: ${{ needs.check-new-commits.outputs.version }}
          SEMVER_VERSION: ${{ needs.check-new-commits.outputs.semver_version }}
          SHORT_HASH: ${{ needs.check-new-commits.outputs.short_hash }}
        run: |
          RELEASE_TAG="v${SEMVER_VERSION}"
          RELEASE_NAME="ROLLER ${SEMVER_VERSION}"

          # Create release notes
          cat > release_notes.md << EOF
          This is an automated nightly build of the ROLLER project.

          **Build Information:**
          - Base Version: ${BASE_VERSION}
          - Release Version: ${SEMVER_VERSION}
          - Commit: ${SHORT_HASH}
          - Build Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

          **Platforms:**
          - Linux x86_64
          - Linux ARM64
          - Windows x86_64
          - macOS ARM64
          - macOS x86_64

          **Note:** This is a pre-release development build and may contain bugs or incomplete features.

          ---
          Built automatically by GitHub Actions
          EOF

          # Delete existing release with same tag if it exists
          gh release delete "$RELEASE_TAG" --yes || true

          # Create new release
          gh release create "$RELEASE_TAG" \
            --title "$RELEASE_NAME" \
            --notes-file release_notes.md \
            --prerelease \
            --target "$(git rev-parse HEAD)" \
            release-assets/*

  cleanup:
    name: Cleanup old nightly releases
    runs-on: ubuntu-latest
    needs: [release]
    if: always() && needs.check-new-commits.outputs.should_build == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup old nightly releases
        run: |
          # Keep only the 5 most recent nightly releases
          # Look for releases with semver pre-release pattern (v*.*.*-dev.*)
          gh release list --limit 50 --json tagName,isPrerelease,createdAt \
            --jq '.[] | select(.isPrerelease == true and (.tagName | test("^v[0-9]+\\.[0-9]+\\.[0-9]+-dev\\.[0-9]+$"))) | .tagName' \
            | tail -n +6 \
            | xargs -I {} gh release delete {} --yes || true
